version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/todo_db
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: tnh
      MYSQL_PASSWORD: mysql12345
      MYSQL_ROOT_PASSWORD: mysql12345